### PR TITLE
fix: added a refresh interval if download status is in progress

### LINKED ISSUE #3270: Status badge shows inaccurate progress when updating without page refresh
### Description

When viewing the download progress of a request via the *Status* badge, and the progress live-updates (without refreshing the page) the progress percentage has increased by the wrong amount. If you then immediately refresh the page, the progress percentage is correct again.

### Version

1.32.0

### Steps to Reproduce

1. Request a season of a TV show
2. Wait for Overseerr to get the download progress from Sonarr and show it on the *Status* badge
3. Wait for Overseerr to update the progress percentage
4. Check progress against what's shown in the Sonarr UI at that time and note that they're not the same
5. Reload Overseerr UI (normal F5 refresh)
6. Check progress against what's shown in the Sonarr UI at that time and note that they're now exactly the same

### Screenshots

_No response_

### Logs

_No response_

### Platform

desktop

### Device

PC, OnePlus 9 Pro

### Operating System

Windows 11, Android 13

### Browser

Edge

### Additional Context

I'm running Overseerr and all other apps as Docker Compose services, they are communicating over a local Docker network. (http)

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

### PR DESCRIPTION
**Pull request by OwsleyJr**
#### Description

Progress bar would not fetch new download status progress if page was not refocused or reloaded. To solve this, I added a refreshInterval if there is a download to watch. I also added in a change to make the download sync editable, in case you want to grab the download status at a faster rate.

- Each component we will call refreshIntervalHelper to see if downloadStatus contains items and then update the timer accordingly.
- Timer set to 5000ms if items are present but this can be altered if needed.
- Download sync schedule is now editable. Editable times are 30, 45, and 60 seconds. 

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`

#### Issues Fixed or Closed

- Fixes #3270

### CODE REVIEW

File: server/lib/settings.ts [hunk 1]
```diff
@@ -410,7 +410,7 @@ class Settings {
           schedule: '0 30 4 * * *',
         },
         'download-sync': {
-          schedule: '0 * * * * *',
+          schedule: '*/60 * * * * *',
```
Comment (danshilm) [inline server/lib/settings.ts:413]: This can be reverted back to 0 to match the the schedule of the other jobs.

File: src/components/MovieDetails/index.tsx [hunk 2]
```diff
@@ -110,6 +111,13 @@ const MovieDetails = ({ movie }: MovieDetailsProps) => {
     mutate: revalidate,
   } = useSWR<MovieDetailsType>(`/api/v1/movie/${router.query.movieId}`, {
     fallbackData: movie,
+    refreshInterval: refreshIntervalHelper(
+      {
+        downloadStatus: movie?.mediaInfo?.downloadStatus,
+        downloadStatus4k: movie?.mediaInfo?.downloadStatus4k,
+      },
+      5000
```
Comment (danshilm) [inline src/components/MovieDetails/index.tsx:119]: 5 seconds interval is way too fast considering that a user can only modify the job schedule to go as fast as 30 seconds in the UI. 
30 or even 15 seconds would be good, though I'm leaning towards the former since IMO a user would need to be actively looking at the progress bar and comparing it to their *arr instance to notice the difference between 30 seconds and 15 seconds interval.

Comment (OwsleyJr) [reply src/components/MovieDetails/index.tsx:119]: I'm okay with changing it to 15 seconds. I feel like any higher might be too long especially since the default is 60.

File: server/lib/settings.ts (hunk 1 above)
Comment (OwsleyJr) [reply server/lib/settings.ts:413]: Ah, yep let me change that.

File: src/components/MovieDetails/index.tsx (hunk 2 above)
Comment (danshilm) [reply src/components/MovieDetails/index.tsx]: Sounds good 👍

File: server/job/schedule.ts [hunk 3]
```diff
@@ -139,7 +139,7 @@ export const startJobs = (): void => {
     id: 'image-cache-cleanup',
     name: 'Image Cache Cleanup',
     type: 'process',
-    interval: 'long',
+    interval: 'minutes',
```
[the remark this answers is not in the document]
Comment (OwsleyJr) [reply server/job/schedule.ts:142]: Not an intended change, I think the comment above it threw me off while I was changing them. Will fix and push.
