### PR TITLE
fix(ui): Handle missing movie/series data

### LINKED ISSUE #858: (small bug) empty table row when rating is unavailable on detail page
**Describe the bug**
Don't show the upper table row if there isn't a rating available for a tv show or movie

**What version of Overseerr are you running?**
1.19.0

You can find it under: Settings -> About -> Version

**To Reproduce**

1. Go to Search for tv show _Out on Stage_
2. Click on _tv show_
3. See error

**Expected behavior**
Don't show an empty table row

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #859: Header cast text is visible even when there is no cast data available
**Describe the bug**
The text "cast" is visible on the detail page even when there is no cast data available

**What version of Overseerr are you running?**
Please fill in the version you are currently running.

You can find it under: Settings -> About -> Version

**To Reproduce**

1. search for Back to Berlin
2. click on it
3. See error

**Expected behavior**
Don't show the cast text and click Arrow when  there isn't any data to show :)

**Screenshots**

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #861: "Invalid Date" when no release date available
**Describe the bug**
The release date field on the movie details page says "Invalid Date" when there is no release date available.

**What version of Overseerr are you running?**
develop-e5966bd3fbfe172f264f4e986ad2aecf29ae1510

**To Reproduce**
1. Open the details page for a movie that does not have a release date (e.g., Guardians of the Galaxy Vol. 3)

**Expected behavior**
No release date row when there is no data.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by TheCatLady**
#### Description

Fix UI issues resulting from missing data.

#### Todos

- [x] Successful build

#### Issues Fixed or Closed by this PR

- Fixes #858
- Fixes #859
- Fixes #861

### CODE REVIEW

**Comment by Magikarplvl4** [comment]
<3

File: src/components/MovieDetails/index.tsx [hunk 1]
```diff
@@ -354,19 +354,23 @@ const MovieDetails: React.FC<MovieDetailsProps> = ({ movie }) => {
...
           <h1 className="text-2xl lg:text-4xl">
             {data.title}{' '}
-            <span className="text-2xl">({data.releaseDate.slice(0, 4)})</span>
+            {data.releaseDate && (
+              <span className="text-2xl">({data.releaseDate.slice(0, 4)})</span>
+            )}
           </h1>
           <span className="mt-1 text-xs lg:text-base lg:mt-0">
-            {(data.runtime ?? 0) > 0 && (
+            {data.runtime || data.genres.length ? (
```
Comment (ankarhem) [inline src/components/MovieDetails/index.tsx:362]: Do we need a conditional operator here?

Comment (TheCatLady) [reply src/components/MovieDetails/index.tsx:362]: Yeah, otherwise it shows a 0. 🤔

Comment (ankarhem) [reply src/components/MovieDetails/index.tsx:362]: You could convert it to a boolean? > 0 or something.

Comment (TheCatLady) [reply src/components/MovieDetails/index.tsx:362]: Yeah but I think this is cleaner, since I'd have to add that for the `genres` arary length as well otherwise?

File: src/components/MovieDetails/index.tsx [hunk 2]
```diff
@@ -354,19 +354,23 @@ const MovieDetails: React.FC<MovieDetailsProps> = ({ movie }) => {
...
-                />{' '}
-                |{' '}
+                {data.runtime ? (
+                  <FormattedMessage
+                    {...messages.runtime}
+                    values={{ minutes: data.runtime }}
+                  />
+                ) : null}
+                {data.runtime && data.genres.length ? ' | ' : ''}
+                {data.genres.map((g) => g.name).join(', ')}
```
Comment (sct) [inline src/components/MovieDetails/index.tsx:371]: Maybe build the string elsewhere and do a `.join(' | ')`? Especially since we might add content ratings here?

Comment (TheCatLady) [reply src/components/MovieDetails/index.tsx:371]: Oh yeah that's a great idea, will make that change now 😄

File: src/components/TvDetails/index.tsx [hunk 3]
```diff
@@ -386,9 +386,9 @@ const TvDetails: React.FC<TvDetailsProps> = ({ tv }) => {
             </span>
           </div>
           <h1 className="text-2xl lg:text-4xl">
-            <span>{data.name}</span>
+            {data.name}{' '}
             {data.firstAirDate && (
-              <span className="ml-2 text-2xl">
+              <span className="text-2xl">
```
Comment (sct) [inline src/components/TvDetails/index.tsx:391]: Why are we not using the `ml-2` here for spacing? This seems like an odd change?

File: src/components/MovieDetails/index.tsx [hunk 4]
```diff
@@ -354,19 +354,23 @@ const MovieDetails: React.FC<MovieDetailsProps> = ({ movie }) => {
           </div>
           <h1 className="text-2xl lg:text-4xl">
             {data.title}{' '}
-            <span className="text-2xl">({data.releaseDate.slice(0, 4)})</span>
+            {data.releaseDate && (
+              <span className="text-2xl">({data.releaseDate.slice(0, 4)})</span>
+            )}
```
Comment (sct) [inline src/components/MovieDetails/index.tsx:359]: This should be changed to be like TvDetails where we using margin for spacing.

File: src/components/TvDetails/index.tsx (hunk 3 above)
Comment (TheCatLady) [reply src/components/TvDetails/index.tsx:391]: I noticed it was different on the MovieDetails and just made it consistent.  Do you prefer `ml-2`?  I think using an actual space is better, since it would make more sense without the formatting.

Comment (sct) [reply src/components/TvDetails/index.tsx:391]: I don't agree using an actual space is better. We should avoid using spaces for layout purposes.

Comment (sct) [reply src/components/TvDetails/index.tsx:391]: The movie details page is just outdated. I fixed TvDetails but never brought the change back over.

Comment (TheCatLady) [reply src/components/TvDetails/index.tsx:391]: Ah okay, sure.  Either way, I just wanted it to be consistent 😺

**Review by sct — APPROVED** [review]
