### PR TITLE
fix(notif): loosen input validation on Pushover settings

### LINKED ISSUE #1165: Notifications - Pushover not accepting User Key
#### Description

Pushover user key is not being accepted and "You must provide a valid user key" is shown below the box. The Application/API token is accepted.

Pushover account has been used for years and have had no issues before.

Tried to save, restart docker etc but remains as "You must provide a valid user key".

Key contains only upper case, lower case and number - no special characters and is 30 characters long.

#### Version

1.20.1

#### Steps to Reproduce

Settings > Notifications > Pushover

I have email and telegram set up and working

#### Expected Behavior

Expected the key to work

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** desktop
- **Device:** MacBook Pro
- **OS:** MacOS 11.2.1
- **Browser:** [Safari

### PR DESCRIPTION
**Pull request by TheCatLady**
#### Description

Our input validation on Pushover tokens/keys is too strict, so relax the check to only verify that 30-character alphanumeric strings are inputted.

Also fix a string on the Telegram notifications page.

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`

#### Issues Fixed or Closed

- Fixes #1165

### CODE REVIEW

File: src/components/Settings/Notifications/NotificationsPushover/index.tsx [hunk 1]
```diff
@@ -41,13 +41,13 @@ const NotificationsPushover: React.FC = () => {
     accessToken: Yup.string()
       .required(intl.formatMessage(messages.validationAccessTokenRequired))
       .matches(
-        /^a[A-Za-z0-9]{29}$/,
+        /^[a-z\d]{30}$/i,
```
Comment (sct) [inline src/components/Settings/Notifications/NotificationsPushover/index.tsx:44]: There is no chance for capital letters?

**Review by sct — CHANGES_REQUESTED** [review]

File: src/components/Settings/Notifications/NotificationsPushover/index.tsx (hunk 1 above)
Comment (TheCatLady) [reply src/components/Settings/Notifications/NotificationsPushover/index.tsx:44]: This does a case-insensitive match 😄

Comment (sct) [reply src/components/Settings/Notifications/NotificationsPushover/index.tsx:44]: Oh I didn't notice the flag. I saw you used \d but didn't see \w so assumed it was only lowercase.

**Review by sct — APPROVED** [review]

File: src/components/Settings/Notifications/NotificationsPushover/index.tsx (hunk 1 above)
Comment (TheCatLady) [reply src/components/Settings/Notifications/NotificationsPushover/index.tsx:44]: `\w` also includes underscores, which is why I didn't use it here. 😉
