### PR TITLE
fix: set editRequest attribute as necessary, allow users to edit their own pending requests, and show 'View Request' button on series pages

### LINKED ISSUE #1444: Can't edit pending movie requests with the View Request button in the Movie Page
#### Description

Today i created a local user named localuser@localuser.test with display name localtest.
I requested the movie The Courier as this local user.
As the admin I opened the movie page and clicked the button View Request.
In the modal i chose a different Quality Profile as the default one and when clicking on the Edit Button an error message "Something went wrong while editing the request." floated in the top right.
I can still edit the request when clicking the cog and clicking the pencil in the side menu.
In the browser console the api call shows "https://overseerr.domain.com/api/v1/request/undefined".

I didnt have an open request of a plex user to try that at the moment so it might happen with those too.

#### Version

What version of Overseerr are you running? (You can find this in Settings → About → Version.)
Stable 1.23.1

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Request a Movie as a local user
2. As the admin open the movie page of the request
3. Click on View Request
4. Click on Edit

#### Expected Behavior

Please provide a clear and concise description of what you expected to happen.

The request should be edited and no error message should show.

#### Screenshots

If applicable, please provide screenshots depicting the problem.

image

image

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

I am running the sctx/overseerr:latest Docker image on an Ubuntu Server LTS 20.0.4 machine.
This behaviour is consistent across Windows 10 Chromium Version 87.0.4280.141 and iPad Pro (iOS 14.4.2) Safari.

#### Additional Context

Please provide any additional information that may be relevant or helpful.

### PR DESCRIPTION
**Pull request by TheCatLady**
#### Description

The `editRequest` attribute is not being set for `RequestModal`s in the `RequestButton` component, causing attempts to edit requests to fail.

Also:
- Fixes the incorrect behavior of showing the `View Request` button to _all_ users when there's an active request. The `View Button` should only be visible if it is the user's own request or the user has the `MANAGE_REQUESTS` permission.
- Allows users to edit their own movie requests if they have the `REQUEST_ADVANCED` (or `MANAGE_REQUESTS`) permission.
- Allows users to edit their own series requests.
- Shows `View Request` on series pages when there is either only one pending request OR the user has a pending request.
- Hides `Request More` if the user already has a pending request.

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`

#### Issues Fixed or Closed

- Fixes #1444

### CODE REVIEW

File: server/routes/request.ts [hunk 1]
```diff
@@ -617,34 +629,38 @@ requestRoutes.put<{ requestId: string }>(
...
-  const requestRepository = getRepository(MediaRequest);
-
-  try {
-    const request = await requestRepository.findOneOrFail({
-      where: { id: Number(req.params.requestId) },
-      relations: ['requestedBy', 'modifiedBy'],
-    });
+requestRoutes.delete(
+  '/:requestId',
+  isAuthenticated(),
```
Comment (sct) [inline server/routes/request.ts:634]: All request routes require `isAuthenticated()` by default so this is unnecessary.

File: server/routes/request.ts [hunk 2]
```diff
@@ -493,7 +493,7 @@ requestRoutes.get('/:requestId', async (req, res, next) => {
 
 requestRoutes.put<{ requestId: string }>(
   '/:requestId',
-  isAuthenticated(Permission.MANAGE_REQUESTS),
+  isAuthenticated(),
```
Comment (sct) [inline server/routes/request.ts:496]: Same here, all the routes require `isAuthenticated()` so this isn't necessary.

File: src/components/RequestButton/index.tsx [hunk 3]
```diff
@@ -23,19 +23,19 @@ const messages = defineMessages({
...
+    'Approve {requestCount, plural, one {Request} other {{requestCount} Requests}}',
   declinerequests:
-    'Decline {requestCount} {requestCount, plural, one {Request} other {Requests}}',
+    'Decline {requestCount, plural, one {Request} other {{requestCount} Requests}}',
   approve4krequests:
-    'Approve {requestCount} 4K {requestCount, plural, one {Request} other {Requests}}',
+    'Approve 4K {requestCount, plural, one {Request} other {{requestCount} Requests}}',
   decline4krequests:
-    'Decline {requestCount} 4K {requestCount, plural, one {Request} other {Requests}}',
+    'Decline 4K {requestCount, plural, one {Request} other {{requestCount} Requests}}',
```
Comment (sct) [inline src/components/RequestButton/index.tsx:38]: I am not sure i understand this change? Won't this come out to be `Approve 4K 2 Requests`?

**Comment by sct** [comment]
With the changes to the `RequestButton` component, we should probably use `React.memo` on it to prevent unnecessary re-renders.

File: src/components/RequestButton/index.tsx [hunk 4]
```diff
@@ -64,26 +64,34 @@ const RequestButton: React.FC<RequestButtonProps> = ({
...
+        : activeRequests[0]
+      : undefined;
+  const active4kRequest =
+    active4kRequests && active4kRequests.length > 0
+      ? active4kRequests.some((request) => request.requestedBy.id === user?.id)
+        ? active4kRequests.find(
+            (request) => request.requestedBy.id === user?.id
+          )
+        : active4kRequests[0]
+      : undefined;
```
Comment (sct) [inline src/components/RequestButton/index.tsx:93]: Might be worth using `useMemo` here?

File: src/components/RequestModal/MovieRequestModal.tsx [hunk 5]
```diff
@@ -206,60 +199,62 @@ const MovieRequestModal: React.FC<RequestModalProps> = ({
...
-            : intl.formatMessage(globalMessages.edit)
+          showEditButton
+            ? intl.formatMessage(messages.edit)
+            : intl.formatMessage(messages.cancel)
+        }
+        okButtonType={showEditButton ? 'primary' : 'danger'}
+        onSecondary={
+          isOwner && showEditButton ? () => cancelRequest() : undefined
+        }
+        secondaryDisabled={isUpdating}
```
Comment (sct) [inline src/components/RequestModal/MovieRequestModal.tsx:231]: we should probably make the secondary style here `danger` for when canceling the request is possible?

**Review by sct — APPROVED** [review]
