### PR TITLE
fix(locale): properly restore display language upon page refresh

### LINKED ISSUE #1645: Language fallsback to App's Settings when refreshing webpage
#### Description

App's General Settings> Display Language , overrides users' display language choices once page is refreshed. Tried it with Greek, English, Spanish, Dutch and German.

#### Version

Develop. 22415642e8602809e3507e5b13dc2f8de3000003

#### Steps to Reproduce and their results

So as an Admin. App is set to English as default language. 

1) I log in into a default user and change the language to something else, such as Greek. Result=whole UI changes to Greek.
2) I then refresh or click on overseerr logo (to refresh) which then reverts back to App's general language setting which is English.

So it override's user's choice to display selected language. In order to fix it I need to log out and log in again and Greek is shown again (if not refreshed). Same happens with other languages as well.

#### Screenshots
**App's Settings. Display language set on English**
Screenshot_2021-05-16 General - Settings - Overseerr

**User's account when logged in. Still not refreshed.**
USER'S ACCOUNT WHEN LOGGED IN - NO REFRESH

**User's account after refreshing. It revert's back to app's general settings. Overriding user's choice.**
user's account after refreshing

#### Device
Tried it with Edge and Firefox. Both in Private and not.
Server is ubuntu server 18.04
Running overseerr in docker

### PR DESCRIPTION
**Pull request by TheCatLady**
#### Description

Currently, the user's locale setting is being lost upon page refresh.

#### Screenshot (if UI-related)

N/A

#### To-Dos

- [x] Successful build `yarn build`
- [x] Translation keys `yarn i18n:extract`

#### Issues Fixed or Closed

- Fixes #1645

### CODE REVIEW

File: server/middleware/auth.ts [hunk 1]
```diff
@@ -29,10 +33,13 @@ export const checkUser: Middleware = async (req, _res, next) => {
...
       req.user = user;
-      req.locale = user.settings?.locale
-        ? user.settings?.locale
-        : settings.main.locale;
     }
+
+    req.locale = user?.settings?.locale
+      ? user.settings.locale
+      : settings.main.locale;
+  } else {
```
Comment (sct) [inline server/middleware/auth.ts:41]: Why not just do all of this once outside of this block before the `next()`?

Comment (TheCatLady) [reply server/middleware/auth.ts:41]: Hm yeah we could do that!

**Review by sct — APPROVED** [review]
