### PR TITLE
fix(plex): do not fail to import Plex users when Plex Home has managed users

### LINKED ISSUE #1698: Import all users from Plex
#### Description

I have a few managed users, which don't have email addresses. I saw in the code there was a .toLowerCase() causing query to fail and I assume it's because emails are null. 

Where I assume the problem is, [link](https://github.com/sct/overseerr/blob/928b8a71cf361b7bc2b8957c621f5b66c4657b1e/server/routes/user/index.ts#L88)

#### Version

e88042ba28f0ec02b67f55273835a29dffd95851, latest develop.

#### Steps to Reproduce

Please tell us how we can reproduce the undesired behavior.

1. Have managed users on plex
2. Import users from plex
3. Error displayed in console for 

#### Expected Behavior

Import successfully

#### Screenshots

image

### PR DESCRIPTION
**Pull request by TheCatLady**
#### Description

Managed users do not have email addresses, which causes the DB query to check for an existing user to fail when we attempt to lowercase the e-mail address.

Also:
- ~~Do not set username when it is the same as the user's email address~~
- Fix weird UX when a user doesn't have a username set
- Make the display name sort on the user list case-insensitive
- Set appropriate placeholder for display name field (so it reflects what the user's display name would be if they do not set a username)
- Hide user email addresses from users without the `Manage Users` permission (unless the user does not have a display name set, in which case their email address is also their display name)

#### Screenshot (if UI-related)

N/A

#### To-Dos

- [x] Successful build `yarn build`

#### Issues Fixed or Closed

- Fixes #1698

### CODE REVIEW

File: src/components/UserProfile/ProfileHeader/index.tsx [hunk 1]
```diff
@@ -65,11 +65,13 @@ const ProfileHeader: React.FC<ProfileHeaderProps> = ({
...
-                ({user.email})
-              </span>
-            )}
+            {user.displayName.toLowerCase() !== user.email.toLowerCase() &&
+              (user.id === loggedInUser?.id ||
+                hasPermission(Permission.MANAGE_USERS)) && (
+                <span className="text-sm text-gray-400 sm:text-lg sm:ml-2">
+                  ({user.email})
+                </span>
+              )}
```
Comment (sct) [inline src/components/UserProfile/ProfileHeader/index.tsx:74]: We already filter email address from the API responses if the user doesn't have the `MANAGE_USERS` permission I the API.

File: server/entity/User.ts [hunk 2]
```diff
@@ -52,7 +52,7 @@ export class User {
   public email: string;
 
   @Column({ nullable: true })
-  public plexUsername: string;
+  public plexUsername?: string;
```
Comment (sct) [inline server/entity/User.ts:55]: This should no longer be optional.

File: src/components/UserProfile/ProfileHeader/index.tsx [hunk 3]
```diff
@@ -65,9 +65,8 @@ const ProfileHeader: React.FC<ProfileHeaderProps> = ({
                 {user.displayName}
               </a>
             </Link>
-            {user.displayName.toLowerCase() !== user.email.toLowerCase() &&
-              (user.id === loggedInUser?.id ||
-                hasPermission(Permission.MANAGE_USERS)) && (
+            {user.email &&
+              user.displayName.toLowerCase() !== user.email.toLowerCase() && (
```
Comment (sct) [inline src/components/UserProfile/ProfileHeader/index.tsx:69]: Why not just force the response from the api endpoint to lowercase everything so we don't need to do this all over the app?

Comment (TheCatLady) [reply src/components/UserProfile/ProfileHeader/index.tsx:69]: @sct Ahh, good call!

File: server/routes/auth.ts [hunk 4]
```diff
@@ -43,7 +43,7 @@ authRoutes.post('/plex', async (req, res, next) => {
     let user = await userRepository
       .createQueryBuilder('user')
       .where('user.plexId = :id', { id: account.id })
-      .orWhere('LOWER(user.email) = :email', {
+      .orWhere('user.email = :email', {
```
Comment (sct) [inline server/routes/auth.ts:46]: I actually wonder if this will work here. Since this is a direct query on the database I don't know if the transformer will be applied.

Comment (TheCatLady) [reply server/routes/auth.ts:46]: @sct It does, just verified!

**Review by sct — APPROVED** [review]
